version: '2.0'
services:
  shiny-mf:
    build: ./
    image: shiny-mf
  shiny-proxy:
    build: ./shinyproxy/
    image: shinyproxy-mf:latest
    container_name: shinyproxy-mf
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - sp-net

networks:
  sp-net:
    name: sp-net
