version: '2.0'
services:
  shinyproxy:
    build: ./shinyproxy/
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - sp-net

networks:
  sp-net:
    name: sp-net
