proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
  specs:
  - id: euler
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: shiny-euler:latest
    container-network: sp-net
  - id: mf
    display-name: Mutation Frequency Dashboard
    description: Custom app which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/mf', 3838, host='0.0.0.0')"]
    container-image: shiny-mf:latest
    container-network: sp-net
logging:
  file:
    shinyproxy.log
